version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10.0
    
    working_directory: ~/repo
    
    steps:
      - checkout
      - run: python --version

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
                    python -m pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: gcc version
          command: |
            gcc --version

      - run:
          name: compile and build
          command: |
                    python setup.py build_ext --inplace

      - run:
          name: run tests
          command: |
                    python setup.py unittests

      - run:
          name: wheel
          command: |
                    python setup.py bdist_wheel
                    mkdir -p test-reports/dist
                    cp dist/*.whl test-reports/dist
                    mkdir -p test-reports/src
                    cp -r  mloptonnx test-reports/src

      - store_artifacts:
          path: test-reports
          destination: test-reports